### ISSUE TITLE
You're leaking your public IP in the screenshots

### ISSUE THREAD

**Issue by BoscoDomingo** [Shihab-glitch/galactic-fastfetch#1]

**Comment by BoscoDomingo** [comment]
@Shihab-glitch You need to force-push (or any other technique to delete Git history). Otherwise the pictures are still available. In any case, your public IP has probably changed, but be wary in the future ;)

**Comment by Shihab-glitch** [comment]
@BoscoDomingo Thank you for your advice. I am new to Github. So, I'm still learning. I'll be more careful from now on.

**Comment by BoscoDomingo** [comment]
No worries, we were all juniors once! I would suggest you take advantage to learn how to squash commits and how to overwrite history so you can remove those old commits that still show that data in a controlled environment where you can mess up without major consequences. It's a great learning opportunity (and also something you rarely should do in a professional context)
